name: projeto_lobao
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
scripts:
  mobx: flutter clean & flutter pub get & flutter pub run build_runner build --delete-conflicting-outputs
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http_multi_server: ^2.2.0
  open_file: ^3.0.1
  url_launcher: ^5.4.10
  font_awesome_flutter: ^8.8.1
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  dio: ^3.0.9
  rxdart: ^0.24.1
  flutter_modular: ^1.2.5+1
  json_annotation: ^3.0.1
  path_provider: ^1.6.10
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  flutter:
    sdk: flutter

dependency_overrides:
  path: ^1.6.4

dev_dependencies:
  mockito: ^4.1.1
  hive_generator: ^0.7.0+2
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
      - assets/mocks/months.json
      - assets/mocks/payroll.json
      - assets/mocks/login.json
